spring:
  application:
    name: atipera
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  api-docs:
    path: /api-docs

service:
  github:
    url: https://api.github.com
    token: :token
